// Words for carpets, the saucer base on the Earth and the F-22 (added to the dictionaries in
// i18n.js).

import { registerStrings } from './i18n.js';

registerStrings('en', {
  // the saucer base
  'saucer.dest.base': 'the Earth saucer base',
  'saucer.home.base': 'To the Earth saucer base',
  'saucer.destSub.base': 'five pads round a control tower',
  'saucer.why.full': 'every pad there is taken',
  'adv.carpet': 'Carpets: two wool make three carpets of its colour (sixteen colours). Put one down on the floor, or on the top of a bed, where it lies over the mattress as its blanket and hangs down its sides; a bed with a blanket is still slept in. Break the bed and its blanket comes off with it.',  // the F-22
  'jet.noPlace': 'The F-22 needs air to fly in: it can only be put down on the Earth.',
  'jet.placed': 'F-22 Raptor parked. Right click it (on a touch screen, tap it) to climb into the cockpit.',
  'jet.noRoom': 'Not enough open, level ground here for an F-22 (it is 19 m long and 13.6 m across the wings).',
  'jet.boarded': 'In the cockpit. It flies where you look. W opens the throttle (held at full: afterburner) for a take-off run, or Space lifts it straight off. H: hover. Left button: cannon; right button: missiles; F: firepower; C: view. Landed, Shift climbs out.',
  'jet.landed': 'Landed. Shift to climb out; a few seconds on the ground and it is rearmed.',
  'jet.rearmed': 'Rearmed: 480 cannon rounds, six AIM-120s and two AIM-9s.',
  'jet.damaged': 'Damaged! Airframe at {hp}%',
  'jet.hit': 'Hit! Airframe at {hp}%',
  'jet.ejected': 'Ejected! Your parachute brings you down.',
  'jet.hover': 'Hover: it holds still in the air, its nose where you look. W A S D move it, Space and Shift up and down; H again to fly on.',
  'jet.flight': 'Flying: afterburner on to get going.',
  'jet.firepower': 'Firepower {n} of 5',
  'jet.noMissiles': 'No missiles left: land to rearm.',
  'jet.fox': 'Fox three! The missile flies to where the circle is.',
  'jet.foxLock': 'Fox three! Locked on.',
  'jet.view.cockpit': 'View: from the cockpit (the wheel or two fingers zoom in)',
  'jet.view.chase': 'View: behind the jet',
  'jet.notYours': 'Someone else is flying that F-22.',
  'jet.hud.landed': 'LANDED',
  'jet.hud.hover': 'HOVER',
  'jet.hud.flight': 'NAV',
  'jet.hud.roll': 'TAKE-OFF RUN',
  'jet.hud.thr': 'THR {n}%',
  'jet.hud.gear': 'GEAR DOWN',
  'jet.hud.fp': 'FIREPOWER',
  'jet.help.keys': 'Mouse: aim (it flies there) · W/S throttle · A/D roll · H hover · left button cannon · right button missile · F firepower · C view · Shift air brake',
  'jet.help.touch': 'Drag: aim (it flies there) · stick: throttle and roll · buttons: cannon, missile, hover, firepower · two fingers: zoom',
  'touch.jetFire': 'GUN',
  'touch.jetMissile': 'MSL',
  'touch.jetHover': 'HOVER',
  'touch.jetPower': 'FP',
  'death.missile': 'Blown up by a missile.',
  'death.jetgun': "Cut down by a fighter's cannon.",
  'death.jetwreck': 'Went down with the jet.',
  'adv.jet': 'F-22 Raptor: six iron blocks, two diamonds, two glass and two TNT make one, at its real size (19 m long, 13.6 m across). Put it down on open ground and right click it to climb in. It is made easy to fly: it goes where you look (the circle in the middle of the HUD), banking into its turns by itself, and Auto-GCAS pulls it up if it is about to fly into the ground. W and S work the throttle (W held at full lights the afterburner), A and D roll it, Shift is the air brake. Take off down a runway with W, or straight up with Space. H hovers: it holds still in the air, its nose where you look, so you can aim exactly (W A S D move it slowly, Space and Shift up and down; Shift on the ground to land, and again to climb out). Left button: the M61 cannon (480 rounds); right button: a missile (six AIM-120 and two AIM-9). Hold the circle on a creature or another player for a moment and the box turns red: locked, the missile goes after it; otherwise it flies to the circle. F sets the firepower (1 to 5): what the rounds and missiles hit is blown apart that hard: blocks, creatures and players, in creative mode too. C: from behind or from the cockpit; the wheel or two fingers zoom. It rearms after a few seconds on the ground. Shot down, you die with it; crashed, you are thrown out under a parachute.',
});

registerStrings('zh', {
  'saucer.dest.base': '地球飞碟基地',
  'saucer.home.base': '去地球飞碟基地',
  'saucer.destSub.base': '五个停机坪围着控制塔',
  'saucer.why.full': '那里的停机坪都停满了',
  'adv.carpet': '毛毯：两块羊毛可以合成三块同色毛毯（共十六种颜色）。可以铺在地上，也可以铺在床上：放在床的上面，它会盖在床垫上、四边垂下来，就是一条被子；盖着毛毯的床照样可以睡。拆掉床，毛毯也会跟着掉下来。',  // the F-22
  'jet.noPlace': 'F-22 需要空气才能飞行：只能放在地球上。',
  'jet.placed': 'F-22 猛禽已停好。右键点击它（触屏上点一下）进入驾驶舱。',
  'jet.noRoom': '这里没有足够大的平地停放 F-22（机身长 19 米，翼展 13.6 米）。',
  'jet.boarded': '已进入驾驶舱。飞机会朝你看的方向飞。按 W 加油门（按住到底开加力）滑跑起飞，或按空格直接垂直升空。H：悬停。左键：机炮；右键：导弹；F：火力；C：视角。着陆后按 Shift 下飞机。',
  'jet.landed': '已着陆。按 Shift 下飞机；在地面停几秒就会自动补满弹药。',
  'jet.rearmed': '弹药已补满：480 发炮弹、6 枚 AIM-120 和 2 枚 AIM-9。',
  'jet.damaged': '飞机受损！机体完好度 {hp}%',
  'jet.hit': '被击中！机体完好度 {hp}%',
  'jet.ejected': '弹射逃生！降落伞带你慢慢落地。',
  'jet.hover': '悬停：飞机停在空中不动，机头指向你看的方向。W A S D 移动，空格/Shift 升降；再按 H 继续飞行。',
  'jet.flight': '恢复飞行：自动开加力加速。',
  'jet.firepower': '火力 {n}/5',
  'jet.noMissiles': '导弹打完了：着陆后会自动补满。',
  'jet.fox': '导弹发射！飞向准星所指的位置。',
  'jet.foxLock': '导弹发射！已锁定目标。',
  'jet.view.cockpit': '视角：驾驶舱（滚轮或双指可以放大）',
  'jet.view.chase': '视角：机尾追随',
  'jet.notYours': '这架 F-22 已经有人在驾驶。',
  'jet.hud.landed': '已着陆',
  'jet.hud.hover': '悬停',
  'jet.hud.flight': '飞行',
  'jet.hud.roll': '起飞滑跑',
  'jet.hud.thr': '油门 {n}%',
  'jet.hud.gear': '起落架 放下',
  'jet.hud.fp': '火力',
  'jet.help.keys': '鼠标：瞄准（飞机朝那里飞）· W/S 油门 · A/D 滚转 · H 悬停 · 左键 机炮 · 右键 导弹 · F 火力 · C 视角 · Shift 减速板',
  'jet.help.touch': '拖动：瞄准（飞机朝那里飞）· 摇杆：油门和滚转 · 按钮：机炮、导弹、悬停、火力 · 双指：缩放',
  'touch.jetFire': '机炮',
  'touch.jetMissile': '导弹',
  'touch.jetHover': '悬停',
  'touch.jetPower': '火力',
  'death.missile': '被导弹炸死了。',
  'death.jetgun': '被战斗机的机炮击中身亡。',
  'death.jetwreck': '随战斗机一起坠毁了。',
  'adv.jet': 'F-22 猛禽战斗机：六个铁块、两颗钻石、两块玻璃和两个 TNT 合成一架，按真实尺寸制作（机长 19 米，翼展 13.6 米）。放在空旷的平地上，右键点击进入驾驶舱。它被设计成很容易驾驶：你看哪里它就飞向哪里（HUD 中间的圆圈），转弯时自动压坡度；快撞地时自动防撞系统（Auto-GCAS）会把飞机拉起来。W/S 控制油门（W 按住到底开加力），A/D 滚转，Shift 是减速板。按 W 滑跑起飞，或按空格垂直升空。H 悬停：飞机停在空中，机头指向你看的方向，方便精准打击（W A S D 慢慢移动，空格/Shift 升降；降到地面就着陆，再按 Shift 下飞机）。左键：M61 机炮（480 发）；右键：发射导弹（6 枚 AIM-120 和 2 枚 AIM-9）。把圆圈对准生物或其他玩家一会儿，方框变红就是锁定了：导弹会追踪它；没锁定时导弹飞向圆圈所指的地方。F 调火力（1 到 5 级）：炮弹和导弹击中的地方按火力大小被摧毁——方块、生物和玩家都会被消灭，创造模式的玩家也会被打死。C 切换机尾视角和驾驶舱视角；滚轮或双指缩放。在地面停几秒自动补满弹药。被击落时你会和飞机一起阵亡；撞地坠毁时会弹射出来，挂着降落伞落地。',
});
