// Words for the survival depth, the new creatures, getting about and the new screens (added to
// the dictionaries in i18n.js).

import { registerStrings } from './i18n.js';

registerStrings('en', {
  'mob.zombie': 'Zombie', 'mob.creeper': 'Creeper', 'mob.skeleton': 'Skeleton', 'mob.spider': 'Spider', 'mob.cow': 'Cow', 'mob.pig': 'Pig',
  'mob.sheep': 'Sheep', 'mob.chicken': 'Chicken', 'mob.zombified_piglin': 'Zombified Piglin', 'mob.blaze': 'Blaze', 'mob.ghast': 'Ghast',
  'mob.enderman': 'Enderman', 'mob.ender_dragon': 'Ender Dragon', 'mob.end_crystal': 'End Crystal', 'mob.villager': 'Villager',
  'mob.iron_golem': 'Iron Golem', 'mob.wolf': 'Wolf', 'mob.cat': 'Cat', 'mob.cod': 'Cod', 'mob.salmon': 'Salmon', 'mob.tropical_fish': 'Tropical Fish',
  'mob.pufferfish': 'Pufferfish', 'mob.squid': 'Squid', 'mob.witch': 'Witch', 'mob.slime': 'Slime', 'mob.phantom': 'Phantom', 'mob.pillager': 'Pillager',
  'mob.vindicator': 'Vindicator', 'mob.evoker': 'Evoker', 'mob.wither': 'Wither', 'mob.wither_skeleton': 'Wither Skeleton', 'mob.guardian': 'Guardian',
  'mob.elder_guardian': 'Elder Guardian', 'mob.shulker': 'Shulker', 'mob.cave_spider': 'Cave Spider', 'mob.horse': 'Horse', 'mob.boat': 'Boat',
  'mob.minecart': 'Minecart', 'mob.tnt': 'TNT', 'mob.evoker_fangs': 'Evoker Fangs',
  'job.none': 'Villager', 'job.farmer': 'Farmer', 'job.fisherman': 'Fisherman', 'job.shepherd': 'Shepherd', 'job.fletcher': 'Fletcher',
  'job.librarian': 'Librarian', 'job.cartographer': 'Cartographer', 'job.cleric': 'Cleric', 'job.armorer': 'Armorer', 'job.weaponsmith': 'Weaponsmith',
  'job.toolsmith': 'Toolsmith', 'job.butcher': 'Butcher', 'job.leatherworker': 'Leatherworker', 'job.mason': 'Mason', 'job.nitwit': 'Nitwit',

  'hud.food': 'Hunger {n}/20',
  'inv.offhand': 'Other hand',
  'inv.tab.potions': 'Brewing', 'inv.tab.transport': 'Transport', 'inv.tab.eggs': 'Spawn eggs',

  'cont.enchant': 'Enchanting Table', 'cont.enchantSlots': 'Enchant', 'cont.enchantHint': 'Put in a tool, a weapon or armour, and lapis lazuli. Each offer costs levels and lapis.',
  'cont.enchantItem': 'Item to enchant', 'cont.lapis': 'Lapis lazuli',
  'cont.brewing': 'Brewing Stand', 'cont.brewingSlots': 'Brew', 'cont.brewingHint': 'Blaze powder fuels it. Water bottles below, an ingredient on top: nether wart first makes an Awkward Potion.',
  'cont.bottle': 'Bottle', 'cont.ingredient': 'Ingredient', 'cont.blaze': 'Blaze powder',
  'cont.trade': 'Trading', 'cont.tradeSlots': 'Trades', 'cont.tradeHint': 'Pick an offer to trade. Villagers restock every morning.',
  'ench.cost': '{n} lapis', 'ench.offer': '{what}: {cost} levels, {lapis} lapis', 'ench.put': 'Put something to enchant on the table.',
  'ench.cannot': 'That can\'t be enchanted.',
  'trade.none': 'This villager has nothing to trade.', 'trade.out': 'Sold out', 'trade.offer': 'Trade for {what} ×{n}',

  'toast.tamed': 'The {name} is yours now',
  'toast.petDied': 'Your {name} died',
  'toast.totem': 'The totem of undying saved you!',
  'toast.wither': 'The Wither has been summoned!',
  'boss.wither': 'Wither',
  'toast.elderCurse': 'Mining fatigue: an elder guardian is near',
  'toast.dismount': 'Sneak (Shift) to get off',
  'toast.elytraOn': 'Elytra on! Jump, then press jump again in the air to glide. While gliding, use a firework rocket to speed up; standing on the ground, look at the sky and use one to take off.',
  'toast.noCity': 'No end city out that way',
  'toast.cam0': 'First person', 'toast.cam1': 'Third person (behind)', 'toast.cam2': 'Third person (in front)',

  'death.wall': 'You flew into a wall', 'death.starve': 'You starved to death', 'death.poison': 'You were poisoned',
  'death.wither': 'You withered away', 'death.magic': 'You were killed by magic', 'death.firework': 'You went off with a bang',
  'death.witch': 'A witch got you', 'death.slime': 'You were squashed by a slime', 'death.phantom': 'A phantom got you',
  'death.pillager': 'You were shot by a pillager', 'death.vindicator': 'A vindicator got you', 'death.evoker': 'You were bitten by evoker fangs',
  'death.wither_skeleton': 'A wither skeleton got you', 'death.guardian': 'A guardian got you', 'death.elder_guardian': 'An elder guardian got you',
  'death.shulker': 'You were shot by a shulker', 'death.cave_spider': 'A cave spider got you', 'death.iron_golem': 'An iron golem got you',
  'death.wolf': 'A wolf got you', 'death.pufferfish': 'You were stung by a pufferfish',

  'keys.swap': 'Swap hands', 'keys.camera': 'Change view', 'keys.dismount': 'Get off (while riding)',
  'key.inAir': '(in mid-air)', 'act.glide': 'Spread the elytra',
  'pause.camera': 'View: {mode}',
});

registerStrings('zh', {
  'mob.zombie': '僵尸', 'mob.creeper': '苦力怕', 'mob.skeleton': '骷髅', 'mob.spider': '蜘蛛', 'mob.cow': '牛', 'mob.pig': '猪',
  'mob.sheep': '羊', 'mob.chicken': '鸡', 'mob.zombified_piglin': '僵尸猪灵', 'mob.blaze': '烈焰人', 'mob.ghast': '恶魂',
  'mob.enderman': '末影人', 'mob.ender_dragon': '末影龙', 'mob.end_crystal': '末地水晶', 'mob.villager': '村民',
  'mob.iron_golem': '铁傀儡', 'mob.wolf': '狼', 'mob.cat': '猫', 'mob.cod': '鳕鱼', 'mob.salmon': '鲑鱼', 'mob.tropical_fish': '热带鱼',
  'mob.pufferfish': '河豚', 'mob.squid': '鱿鱼', 'mob.witch': '女巫', 'mob.slime': '史莱姆', 'mob.phantom': '幻翼', 'mob.pillager': '掠夺者',
  'mob.vindicator': '卫道士', 'mob.evoker': '唤魔者', 'mob.wither': '凋灵', 'mob.wither_skeleton': '凋灵骷髅', 'mob.guardian': '守卫者',
  'mob.elder_guardian': '远古守卫者', 'mob.shulker': '潜影贝', 'mob.cave_spider': '洞穴蜘蛛', 'mob.horse': '马', 'mob.boat': '船',
  'mob.minecart': '矿车', 'mob.tnt': 'TNT', 'mob.evoker_fangs': '唤魔者尖牙',
  'job.none': '村民', 'job.farmer': '农民', 'job.fisherman': '渔夫', 'job.shepherd': '牧羊人', 'job.fletcher': '制箭师',
  'job.librarian': '图书管理员', 'job.cartographer': '制图师', 'job.cleric': '牧师', 'job.armorer': '盔甲匠', 'job.weaponsmith': '武器匠',
  'job.toolsmith': '工具匠', 'job.butcher': '屠夫', 'job.leatherworker': '皮匠', 'job.mason': '石匠', 'job.nitwit': '傻子',

  'hud.food': '饥饿值 {n}/20',
  'inv.offhand': '副手',
  'inv.tab.potions': '酿造', 'inv.tab.transport': '交通', 'inv.tab.eggs': '刷怪蛋',

  'cont.enchant': '附魔台', 'cont.enchantSlots': '附魔', 'cont.enchantHint': '放入工具、武器或盔甲，再放青金石。每个选项都要消耗等级和青金石。',
  'cont.enchantItem': '要附魔的物品', 'cont.lapis': '青金石',
  'cont.brewing': '酿造台', 'cont.brewingSlots': '酿造', 'cont.brewingHint': '烈焰粉作燃料。下面放水瓶，上面放材料：先放下界疣做出粗制的药水。',
  'cont.bottle': '瓶子', 'cont.ingredient': '材料', 'cont.blaze': '烈焰粉',
  'cont.trade': '交易', 'cont.tradeSlots': '交易', 'cont.tradeHint': '点一项来交易。村民每天早上补货。',
  'ench.cost': '{n} 个青金石', 'ench.offer': '{what}：{cost} 级，{lapis} 个青金石', 'ench.put': '先在附魔台上放要附魔的东西。',
  'ench.cannot': '这个不能附魔。',
  'trade.none': '这个村民没有东西可交易。', 'trade.out': '已售罄', 'trade.offer': '换取 {what} ×{n}',

  'toast.tamed': '{name}被你驯服了',
  'toast.petDied': '你的{name}死了',
  'toast.totem': '不死图腾救了你一命！',
  'toast.wither': '凋灵被召唤出来了！',
  'boss.wither': '凋灵',
  'toast.elderCurse': '挖掘疲劳：附近有远古守卫者',
  'toast.dismount': '按潜行键（Shift）下来',
  'toast.elytraOn': '穿上鞘翅了！跳起来后，在空中再按一次跳跃就会展开滑翔。滑翔时使用烟花火箭加速；站在地上抬头看天空使用烟花，可以直接起飞。',
  'toast.noCity': '这个方向没有末地城',
  'toast.cam0': '第一人称', 'toast.cam1': '第三人称（背后）', 'toast.cam2': '第三人称（正面）',

  'death.wall': '你撞墙了', 'death.starve': '你饿死了', 'death.poison': '你中毒身亡', 'death.wither': '你凋零了',
  'death.magic': '你被魔法杀死了', 'death.firework': '你随着一声巨响消逝了', 'death.witch': '你被女巫杀死了', 'death.slime': '你被史莱姆压扁了',
  'death.phantom': '你被幻翼杀死了', 'death.pillager': '你被掠夺者射杀了', 'death.vindicator': '你被卫道士杀死了', 'death.evoker': '你被唤魔者的尖牙咬死了',
  'death.wither_skeleton': '你被凋灵骷髅杀死了', 'death.guardian': '你被守卫者杀死了', 'death.elder_guardian': '你被远古守卫者杀死了',
  'death.shulker': '你被潜影贝射杀了', 'death.cave_spider': '你被洞穴蜘蛛杀死了', 'death.iron_golem': '你被铁傀儡杀死了',
  'death.wolf': '你被狼咬死了', 'death.pufferfish': '你被河豚刺死了',

  'keys.swap': '交换主副手', 'keys.camera': '切换视角', 'keys.dismount': '下坐骑（骑乘时）',
  'key.inAir': '（在空中）', 'act.glide': '展开鞘翅滑翔',
  'pause.camera': '视角：{mode}',
});

// adventures: short how-tos on the help screen
registerStrings('en', {
  'adv.hunger': 'Hunger: running and jumping make you hungry; hold the use button to eat. Full, you heal; starving, you don\'t.',
  'adv.enchant': 'Enchanting: an enchanting table (book, diamonds, obsidian) with bookshelves around it; experience from creatures, ores, smelting, trading and fishing pays for it.',
  'adv.brew': 'Brewing: a brewing stand fuelled by blaze powder turns water bottles into potions. Nether wart first, then the ingredient; gunpowder makes them splash.',
  'adv.pets': 'Animals: wheat, carrots or seeds bring two into love and a baby follows. Bones tame wolves, raw fish tames cats; use a tamed pet to make it sit. Shears for wool, a bucket for milk.',
  'adv.trade': 'Villages: use a villager to trade emeralds. Iron golems guard them; a pumpkin on a T of iron blocks makes one.',
  'adv.ride': 'Riding: boats go on water, minecarts on rails. Tame a horse by riding it until it stops throwing you, then saddle it. Shift gets you off.',
  'adv.elytra': 'Elytra (from end cities): wear them in the chest slot (or use them from your hand). Jump, then press jump again in the air to glide; sneak to fold them. A firework rocket used while gliding sends you flying the way you look, trailing sparks; standing on the ground, look at the sky and use one to take off.',
  'adv.plate': 'Pressure plates open the doors beside them while something stands on them; iron doors only open that way.',
});
registerStrings('zh', {
  'adv.hunger': '饥饿：奔跑和跳跃会消耗饱食度；按住使用键吃东西。吃饱会回血，饿着不会。',
  'adv.enchant': '附魔：附魔台（书、钻石、黑曜石）周围摆上书架更强；打怪和挖矿获得的经验用来附魔。',
  'adv.brew': '酿造：酿造台用烈焰粉作燃料，把水瓶酿成药水。先放下界疣，再放材料；加火药变成喷溅药水。',
  'adv.pets': '动物：用小麦、胡萝卜或种子让两只动物进入恋爱模式，就会生出幼崽。用骨头驯服狼，用生鱼驯服猫；对驯服的宠物使用可让它坐下。剪刀剪羊毛，桶挤牛奶。',
  'adv.trade': '村庄：对村民使用可以用绿宝石交易。铁傀儡守护村庄；在 T 形铁块上放南瓜能造一个。',
  'adv.ride': '骑乘：船在水上走，矿车在铁轨上跑。骑马直到它不再把你甩下来就驯服了，再装上鞍。按 Shift 下来。',
  'adv.elytra': '鞘翅（在末地城里找）：穿在胸甲栏（拿在手里按使用键也能穿上）。跳起来后在空中再按一次跳跃就会展开滑翔，按潜行收起。滑翔时使用烟花火箭会朝你看的方向猛地加速，身后拖出火花；站在地上抬头看天空使用烟花，可以直接起飞。',
  'adv.plate': '压力板：有东西站在上面时会打开旁边的门；铁门只能这样打开。',
});

// weather on a server
registerStrings('en', {
  'set.weather.desc': 'Changing brings rain now and then, with the odd thunderstorm. Deserts stay dry; cold biomes get snow. On a server, Changing is the server\'s weather, the same for everyone; pick another to see your own.',
});
registerStrings('zh', {
  'set.weather.desc': '"多变"会不时下雨，偶尔还有雷暴。沙漠不下雨，寒冷地区会下雪。联机时"多变"就是服务器的天气，所有人看到的都一样；选其他选项则只改变你自己看到的天气。',
});

registerStrings('en', { 'touch.camera': 'Change view' });
registerStrings('zh', { 'touch.camera': '切换视角' });

// talking with villagers
registerStrings('en', {
  'talk.cannot': 'This villager can\'t talk just now.',
  'talk.you': 'a traveller',
  'talk.quest': '{name} wants {item} ×{n} (you have {have}) → reward: {reward} ×{rn}',
  'talk.deliver': 'Hand over',
  'talk.discount': '{pct}% off today',
  'talk.gift': 'Give: {item}',
  'talk.trade': 'Trade',
  'talk.send': 'Say',
  'talk.placeholder': 'Say something…',
  'talk.listening': 'Listening… speak now',
  'talk.mic': 'Speak instead of typing',
  'talk.micDenied': 'The microphone is blocked: allow it in the browser to talk out loud.',
  'talk.micFail': 'Talking out loud doesn\'t work on this device or network. Type instead!',
  'talk.brainAi': 'Answers by the ATRIA model',
  'talk.brainOffline': 'Simple answers (no language model reachable)',
  'talk.quickList': 'Hello!|What\'s your name?|Got any work for me?|Any news?|Can you do it cheaper?|Follow me!|Tell me a story|Bye!',
  'talk.gotGift': '{name} gave you {item} ×{n}',
  'talk.newQuest': 'New task from {name}: {item} ×{n}',
  'talk.gotDiscount': '{name} gives you {pct}% off today',
  'talk.questDone': 'Task done! You got {item} ×{n}',
  'talk.child': 'Child',
  'talk.hintKeys': 'Right click or Enter: talk',
  'talk.hintTouch': 'Tap: talk',
  'talk.hintPad': 'LT: talk',
  'talk.hearts': 'Friendship: {n} of 5 hearts',
  'set.villagerVoice': 'Villagers speak aloud',
  'set.villagerVoice.desc': 'Villagers say their words in your device\'s voice, quieter the further away they are. Off: their words only appear above their heads.',
  'set.villagerVolume': 'Villager voice volume',
  'set.voiceTest': 'Test the villagers\' voice',
  'set.voiceTest.btn': 'Test',
  'set.voiceTest.desc': 'Says a line now and tells you whether this device can speak it.',
  'voice.testLine': 'Hello! I am a villager. Can you hear me?',
  'voice.testing': 'Speaking…',
  'voice.r.ok': 'Working: speaking with "{voice}" ({n} English voices on this device). If you still hear nothing, turn the media volume up.',
  'voice.r.okDefault': 'Working: speaking with the device\'s own voice. If you still hear nothing, turn the media volume up.',
  'voice.r.unsupported': 'This browser can\'t speak text (often the case for pages opened inside WeChat, QQ or other apps). Open the game in Safari, Chrome or the phone\'s own browser.',
  'voice.r.novoice': 'This device has no English voice: add one in its settings (iPhone/iPad: Settings → Accessibility → Spoken Content → Voices; Android: Settings → text-to-speech, download the language).',
  'voice.r.silent': 'The device didn\'t start speaking. Tap Test once more; on an iPhone or iPad check it isn\'t muted and turn the volume up.',
  'voice.r.notAllowed': 'The browser didn\'t let the page speak. Tap Test once more.',
  'voice.r.error': 'The device\'s speech failed ({err}). Check its text-to-speech settings, or try another browser.',
  'voice.r.off': '(Villagers speaking aloud is switched off above.)',
  'talk.noVoice': 'This browser can\'t speak, so the villagers\' words only appear as text (Settings → Sound: Test).',
  'adv.talk': 'Villagers: right click (or tap) one to talk. Each has a name, a character and a memory: they remember you, what you said and did, pass on village gossip, set you tasks, give friends little presents and can be talked into a discount or into following you. Type, pick a ready-made line, or speak (where the device can). Sneak and right click to go straight to trading.',
  'adv.trade': 'Villages: trade emeralds with villagers (from the talk screen, or sneak and right click). Iron golems guard them; a pumpkin on a T of iron blocks makes one.',
  biomes: 'Ocean|Beach|Plains|Forest|Birch Forest|Taiga|Snowy Taiga|Desert|Mountains|River|Jungle|Savanna|Swamp|Badlands|Cherry Grove|Dark Forest',
});
registerStrings('zh', {
  'talk.cannot': '这个村民现在没法说话。',
  'talk.you': '一个外乡人',
  'talk.quest': '{name}想要：{item} ×{n}（你有 {have} 个）→ 奖励：{reward} ×{rn}',
  'talk.deliver': '交付',
  'talk.discount': '今天打 {pct}% 折扣',
  'talk.gift': '送礼：{item}',
  'talk.trade': '交易',
  'talk.send': '说',
  'talk.placeholder': '想说点什么……',
  'talk.listening': '在听……请说话',
  'talk.mic': '用说话代替打字',
  'talk.micDenied': '麦克风被禁止了：在浏览器里允许后就能说话聊天。',
  'talk.micFail': '这台设备或网络听不了语音，请打字吧！',
  'talk.brainAi': '由 ATRIA 大模型回答',
  'talk.brainOffline': '简单对话（没有连上大模型）',
  'talk.quickList': '你好！|你叫什么名字？|有什么活儿要帮忙吗？|最近有什么新鲜事？|能便宜点吗？|跟我来！|讲个故事吧|再见！',
  'talk.gotGift': '{name}送给你 {item} ×{n}',
  'talk.newQuest': '{name}的新任务：{item} ×{n}',
  'talk.gotDiscount': '{name}今天给你打 {pct}% 折扣',
  'talk.questDone': '任务完成！得到 {item} ×{n}',
  'talk.child': '小孩',
  'talk.hintKeys': '右键或回车：交谈',
  'talk.hintTouch': '点一下：交谈',
  'talk.hintPad': 'LT：交谈',
  'talk.hearts': '好感度：5 颗心里有 {n} 颗',
  'set.villagerVoice': '村民说话出声',
  'set.villagerVoice.desc': '村民用设备自带的声音把话说出来，离得越远声音越小。关掉后只在头顶显示文字。',
  'set.villagerVolume': '村民说话音量',
  'set.voiceTest': '试听村民说话',
  'set.voiceTest.btn': '试听',
  'set.voiceTest.desc': '马上说一句话，并告诉你这台设备能不能朗读。',
  'voice.testLine': '你好！我是村民，你能听到我说话吗？',
  'voice.testing': '正在朗读……',
  'voice.r.ok': '可以朗读：正在用「{voice}」（这台设备有 {n} 个中文语音）。如果还是听不到，请把媒体音量调大。',
  'voice.r.okDefault': '可以朗读：用的是设备自带的声音。如果还是听不到，请把媒体音量调大。',
  'voice.r.unsupported': '这个浏览器不能朗读文字（在微信、QQ 等 App 里打开的网页常常这样）。请用 Safari、Chrome 或手机自带的浏览器打开游戏。',
  'voice.r.novoice': '这台设备没有中文语音：请在系统设置里添加（iPhone/iPad：设置 → 辅助功能 → 朗读内容 → 声音；安卓：设置 → 文字转语音，下载中文语音包）。',
  'voice.r.silent': '设备没有开始朗读。再点一次"试听"试试；iPhone/iPad 请确认没有静音，并把音量调大。',
  'voice.r.notAllowed': '浏览器没有允许网页朗读，请再点一次"试听"。',
  'voice.r.error': '设备的朗读出错了（{err}）。请检查系统的文字转语音设置，或者换一个浏览器试试。',
  'voice.r.off': '（上面的"村民说话出声"现在是关着的。）',
  'talk.noVoice': '这个浏览器不能朗读，村民的话只会显示文字（设置 → 声音里可以试听）。',
  'adv.talk': '村民：对村民右键（手机上点一下）就能聊天。每个村民都有自己的名字、性格和记忆：记得你、记得你说过什么做过什么，会传村里的八卦，会派任务，会给好朋友送小礼物，还能被你说动打折，或者跟着你走。可以打字、点现成的话，也可以直接说话（设备支持的话）。蹲下再右键可以直接交易。',
  'adv.trade': '村庄：用绿宝石和村民交易（在聊天界面里点“交易”，或者蹲下右键）。铁傀儡守护村庄；在 T 形铁块上放南瓜能造一个。',
  biomes: '海洋|沙滩|平原|森林|白桦林|针叶林|积雪针叶林|沙漠|山地|河流|丛林|热带草原|沼泽|恶地|樱花林|黑森林',
});
