// Words for carrying people and creatures, the villagers' new ways and the flying saucer (added
// to the dictionaries in i18n.js).

import { registerStrings } from './i18n.js';

registerStrings('en', {
  'touch.carry': 'Pick up / put down',
  'carry.up': 'Lift',
  'carry.down': 'Put down',
  'carry.heavy': 'Too heavy to lift!',
  'carry.no': 'It won\'t let you pick it up!',
  'carry.carried': '{name} picked you up! Jump three times to wriggle free',
  'carry.free': 'You wriggled free!',
  'adv.carry': 'Carrying: look at a villager, a friend or an animal close by and press G (the touch screen\'s Lift button, or the controller\'s D-pad right) to pick it up in your arms. Press it again, or right click, to put it down; while running you throw it a little way. Put a villager down far from its home and it lives there instead.',
  'help.carry': 'Pick up / put down (a villager, a friend, an animal)',
  'wp.set': 'Marked on your screen: {place}, about {d} blocks to the {dir}',
  'wp.dist': '{d} blocks',
  'wp.found': 'Found it: {place}!',
  'wp.foundBy': '{name} will be pleased.',
  'wp.clear': 'Remove the marker ({place})',
  'saucer.title': 'Flying saucer',
  'saucer.fly': 'Fly it myself',
  'saucer.asking': 'Asking to come aboard…',
  'saucer.boarded': '{name} came aboard',
  'saucer.aboard': 'Aboard {name}\'s saucer! Look about to swing the camera; sneak, once it has landed, to get off.',
  'saucer.aboardHint': 'On {name}\'s saucer · sneak once it has landed to get off',
  'saucer.noBoard.flying': 'It\'s in the air: wait till it lands',
  'saucer.noBoard.full': 'No seats left',
  'saucer.noBoard.gone': 'That saucer has nobody at the controls',
  'saucer.flyOn': 'Carry on flying',
  'saucer.manualHint': 'You\'re flying: move to steer (the way the camera looks), jump to go up, sneak to come down, sprint for speed. Over flat ground, keep coming down (not sprinting) and it slows and lands itself; right click or Enter for the panel.',
  'saucer.outOfFuel': 'Out of fuel: the saucer is coming down',
  'saucer.uneven': 'Too uneven to land here',
  'saucer.touchdown': 'Touchdown!',
  'saucer.bump': 'Bonk! The saucer bounced off, not a scratch on it',
  'saucer.where': 'Where to?',
  'saucer.howLong': 'How long a trip?',
  'saucer.t30': '30 s', 'saucer.t60': '1 min', 'saucer.t180': '3 min', 'saucer.tCustom': 'Custom',
  'saucer.secs': '{n} s', 'saucer.mins': '{m} min', 'saucer.minSecs': '{m} min {s} s',
  'saucer.go': 'Take off (autopilot)',
  'saucer.exit': 'Climb out',
  'saucer.addFuel': 'Add fuel',
  'saucer.fuel': 'Fuel {n}/{max}',
  'saucer.fuelInf': 'Fuel: unlimited (creative)',
  'saucer.fuelHint': 'Coal or charcoal 1, blaze rod 2, lava bucket 8',
  'saucer.cost': 'Fuel {n}',
  'saucer.dest.earth': 'the Earth', 'saucer.dest.moon': 'the Moon', 'saucer.dest.mars': 'Mars', 'saucer.dest.jupiter': 'the Jupiter station', 'saucer.dest.saturn': 'the Saturn station',
  'saucer.home.earth': 'Back to its pad', 'saucer.home.moon': 'To the Moon\'s pad', 'saucer.home.mars': 'To the pad on Mars', 'saucer.home.jupiter': 'To the station\'s pad', 'saucer.home.saturn': 'To the station\'s pad',
  'saucer.destSub.earth': 'its own launch pad', 'saucer.destSub.moon': 'the launch pad, under the Earth', 'saucer.destSub.mars': 'the launch pad on the red planet', 'saucer.destSub.jupiter': 'over a sea of storm clouds', 'saucer.destSub.saturn': 'under the rings',
  'saucer.why.here': 'You\'re here', 'saucer.why.fuel': 'Not enough fuel', 'saucer.why.noPad': 'No launch pad yet', 'saucer.why.nowhere': 'It can\'t take off from here',
  'saucer.placed': 'Saucer down in front of you! Right click it (from under it too) to climb in.',
  'saucer.noRoom.room': 'No room for the saucer here: it needs a clear space about 55 blocks across',
  'saucer.noRoom.uneven': 'Too uneven here for the saucer\'s legs',
  'saucer.crew.count': '{n}/{max} aboard · {v} villagers',
  'saucer.crew.invite': 'Invite villagers aboard',
  'saucer.crew.unload': 'Let the villagers off',
  'saucer.crew.none': 'No villagers near enough to ask aboard',
  'saucer.crew.came': '{n} villagers came aboard ({scared} too scared)',
  'saucer.crew.off': '{n} villagers got off: they live here now',
  'saucer.crew.empty': 'No villagers aboard',
  'saucer.view.bridge': 'On the bridge (C again: outside)',
  'saucer.view.orbit': 'Outside, round the saucer',
  'saucer.noPlace': 'A saucer won\'t work here',
  'saucer.notYours': 'Another player\'s game is running this saucer',
  'saucer.tankFull': 'The tank is full',
  'saucer.noFuel': 'No fuel on you (coal, charcoal, blaze rods, lava)',
  'saucer.launch': 'Off to {place}. Countdown!',
  'saucer.launchAir': 'Off to {place}: the autopilot has it!',
  'saucer.arrived': 'Landed on the pad: {place}.',
  'saucer.landedHint': 'Right click for the flight panel, Shift to climb out.',
  'saucer.hintKeys': 'Right click or Enter: flight panel · Shift: climb out · wheel: zoom · C: bridge',
  'saucer.hintTouch': 'Tap: flight panel · down button: climb out',
  'saucer.hintPad': 'A: flight panel · B: climb out',
  'saucer.flyKeys': 'Space: up · Shift: down · R: faster · right click or Enter: flight panel · wheel: zoom · C: bridge',
  'saucer.flyTouch': 'Jump: up · down button: down · tap: flight panel',
  'saucer.flyPad': 'A: up · B: down · LT: flight panel',
  'trip.to': 'To {place}', 'trip.left': '{t} to go', 'trip.countdown': 'Lift-off in {n}…',
  'trip.zoomIn': 'Closer', 'trip.zoomOut': 'Further out',
  'adv.saucer': 'Flying saucer (creative has it; in survival: 4 iron blocks, 4 glass, 2 lanterns, 2 diamonds): a mothership 55 blocks across. Use it on the ground and it settles a little in front of you on six legs that reach down to uneven ground (it needs a clear patch about that wide); right click any part of it and a beam lifts you up into the pilot\'s seat under the glass dome. Pick where to go (the Earth, the Moon, Mars, the stations over Jupiter and Saturn) and how long the trip should take (30 s to 15 min, to watch the view), and the autopilot spools up its engines, lifts off on a column of fire that lights the ground round it red, flies out of the air, round the planet and across space, and lands on the launch pad there (at a station, on its docking deck). Look about to swing the camera round it; the wheel zooms; C switches to the view from the bridge and back. In survival it runs on fuel: right click it holding coal, blaze rods or lava, or use the panel\'s Add fuel. Fly it myself hands you the controls: steer where the camera looks, jump to climb, sneak to come down, sprint for speed; keep coming down over flat ground and it lands itself, and bumps just bounce it off. It seats sixteen besides the pilot: landed, Invite villagers aboard asks the villagers near it in (friends always come, others may not want to), and Let the villagers off sets them down wherever you are: they make their home there. Landed, sneak to climb out. On a server, right click someone\'s landed saucer to ride along (up to sixteen, villagers included).',
  'adv.village': 'Village life: villagers know of real places round about. Ask one "Anything interesting near here?" and it may tell you of a temple, a mansion or a mineshaft, marked on your screen until you get there (the pause menu takes the marker away). They chat with each other, wave when a friend comes by, cheer when you see off a monster, mind you knocking their houses about, run indoors from storms, and come to look when you drop out of the sky.',
});

registerStrings('zh', {
  'touch.carry': '抱起 / 放下',
  'carry.up': '抱',
  'carry.down': '放下',
  'carry.heavy': '太重了，抱不动！',
  'carry.no': '它可不让你抱！',
  'carry.carried': '{name}把你抱了起来！连按三下跳跃可以挣脱',
  'carry.free': '你挣脱了！',
  'adv.carry': '公主抱：看着附近的村民、朋友或小动物，按 G（触屏上的"抱"按钮，手柄方向键 →）就能把它抱起来。再按一次或者点右键就放下；疾跑时放手会把它扔出去一小段。把村民抱到离它家很远的地方放下，它就会在那里安家。',
  'help.carry': '抱起 / 放下（村民、朋友、小动物）',
  'wp.set': '{place}在{dir}，大约{d}格远：已在屏幕上标出',
  'wp.dist': '{d} 格',
  'wp.found': '你找到了{place}！',
  'wp.foundBy': '{name}知道了一定很高兴。',
  'wp.clear': '取消标记（{place}）',
  'saucer.title': '飞碟',
  'saucer.fly': '自己驾驶',
  'saucer.asking': '正在请求上飞碟…',
  'saucer.boarded': '{name}上了你的飞碟',
  'saucer.aboard': '你坐上了{name}的飞碟！转动视角可以绕着看；飞碟着陆后按下蹲键下来。',
  'saucer.aboardHint': '坐在{name}的飞碟上 · 着陆后按下蹲键下来',
  'saucer.noBoard.flying': '飞碟正在飞，等它着陆再上',
  'saucer.noBoard.full': '座位满了',
  'saucer.noBoard.gone': '这架飞碟上没有驾驶员',
  'saucer.flyOn': '继续自己驾驶',
  'saucer.manualHint': '你在驾驶飞碟：移动键控制方向（朝镜头看的方向飞），跳跃上升，下蹲下降，疾跑加速。在平地上方按住下蹲（不按疾跑），它会自己减速着陆；右键或回车打开面板。',
  'saucer.outOfFuel': '燃料用完了，飞碟正在慢慢降落',
  'saucer.uneven': '这里不平，没法降落',
  'saucer.touchdown': '着陆成功！',
  'saucer.bump': '砰！飞碟弹开了，一点事都没有',
  'saucer.where': '去哪里？',
  'saucer.howLong': '飞多久？',
  'saucer.t30': '30 秒', 'saucer.t60': '1 分钟', 'saucer.t180': '3 分钟', 'saucer.tCustom': '自定义',
  'saucer.secs': '{n} 秒', 'saucer.mins': '{m} 分钟', 'saucer.minSecs': '{m} 分 {s} 秒',
  'saucer.go': '起飞（自动驾驶）',
  'saucer.exit': '下飞碟',
  'saucer.addFuel': '加燃料',
  'saucer.fuel': '燃料 {n}/{max}',
  'saucer.fuelInf': '燃料：无限（创造模式）',
  'saucer.fuelHint': '煤炭或木炭 1，烈焰棒 2，岩浆桶 8',
  'saucer.cost': '需要燃料 {n}',
  'saucer.dest.earth': '地球', 'saucer.dest.moon': '月球', 'saucer.dest.mars': '火星', 'saucer.dest.jupiter': '木星空间站', 'saucer.dest.saturn': '土星空间站',
  'saucer.home.earth': '回到发射台', 'saucer.home.moon': '去月球发射台', 'saucer.home.mars': '去火星发射台', 'saucer.home.jupiter': '去空间站的停机坪', 'saucer.home.saturn': '去空间站的停机坪',
  'saucer.destSub.earth': '它自己的发射台', 'saucer.destSub.moon': '发射台正对着地球', 'saucer.destSub.mars': '红色星球上的发射台', 'saucer.destSub.jupiter': '漂在风暴云海上', 'saucer.destSub.saturn': '就在光环下面',
  'saucer.why.here': '就在这里', 'saucer.why.fuel': '燃料不够', 'saucer.why.noPad': '还没有发射台', 'saucer.why.nowhere': '这里没法起飞',
  'saucer.placed': '飞碟放在你前面了！右键它（站在它下面也行）就能坐进去。',
  'saucer.noRoom.room': '这里放不下飞碟：需要一块直径约 55 格的空地',
  'saucer.noRoom.uneven': '这里地面太不平，飞碟的腿够不着',
  'saucer.crew.count': '飞碟上 {n}/{max} 人 · 村民 {v} 位',
  'saucer.crew.invite': '邀请附近的村民上船',
  'saucer.crew.unload': '让村民下船',
  'saucer.crew.none': '附近没有可以邀请的村民',
  'saucer.crew.came': '{n} 位村民上了飞碟（{scared} 位不敢上）',
  'saucer.crew.off': '{n} 位村民下了飞碟，他们会在这里住下',
  'saucer.crew.empty': '飞碟上没有村民',
  'saucer.view.bridge': '舰桥视角（再按 C 回到外面）',
  'saucer.view.orbit': '外部视角，绕着飞碟看',
  'saucer.noPlace': '这里用不了飞碟',
  'saucer.notYours': '这架飞碟正由另一位玩家的游戏控制着',
  'saucer.tankFull': '油箱满了',
  'saucer.noFuel': '身上没有燃料（煤炭、木炭、烈焰棒、岩浆桶）',
  'saucer.launch': '目标：{place}。倒计时开始！',
  'saucer.launchAir': '目标：{place}。自动驾驶接管！',
  'saucer.arrived': '已降落在{place}的发射台。',
  'saucer.landedHint': '右键打开飞行面板，Shift 下飞碟。',
  'saucer.hintKeys': '右键或回车：飞行面板 · Shift：下飞碟 · 滚轮：远近 · C：舰桥视角',
  'saucer.hintTouch': '点屏幕：飞行面板 · 下蹲键：下飞碟',
  'saucer.hintPad': 'A：飞行面板 · B：下飞碟',
  'saucer.flyKeys': '空格：上升 · Shift：下降 · R：加速 · 右键或回车：飞行面板 · 滚轮：远近 · C：舰桥视角',
  'saucer.flyTouch': '跳跃键：上升 · 下蹲键：下降 · 点屏幕：飞行面板',
  'saucer.flyPad': 'A：上升 · B：下降 · LT：飞行面板',
  'trip.to': '前往{place}', 'trip.left': '还有 {t}', 'trip.countdown': '{n} 秒后起飞…',
  'trip.zoomIn': '拉近', 'trip.zoomOut': '拉远',
  'adv.saucer': '飞碟（创造模式直接有；生存模式用 4 个铁块、4 块玻璃、2 个灯笼、2 颗钻石合成）：一艘直径 55 格的母舰。对着地面使用，它会停在你前方不远处，六条着陆腿会自己伸长去够高低不平的地面（需要差不多这么大一片空地）；右键飞碟的任何部位，一道光束就会把你送进玻璃穹顶下的驾驶座。选好去哪里（地球、月球、火星、木星和土星的空间站）和飞多久（30 秒到 15 分钟，想多看看风景就选长一点），自动驾驶会先让引擎轰鸣蓄力，然后喷着把地面映得通红的火柱起飞，冲出大气层，绕着星球转弯飞向太空，最后降落在那边的发射台上（空间站则停在它的停泊平台上）。飞行时转动视角可以绕着飞碟看，滚轮调远近，按 C 切换到舰桥视角再按一次切回来。生存模式要加燃料：拿着煤炭、烈焰棒或岩浆桶右键飞碟，或者在面板里点"加燃料"。点"自己驾驶"就能手动飞：朝镜头方向飞，跳跃上升，下蹲下降，疾跑加速；在平地上方一直下降它会自己着陆，撞到东西只会弹开。除了驾驶员还能坐 16 个人：落地后点"邀请附近的村民上船"可以请附近的村民上来（好朋友一定会来，其他人不一定愿意），点"让村民下船"就让他们在当前地点下船，他们会在那里安家。落地后按下蹲走出飞碟。多人游戏里右键别人落地的飞碟可以搭乘（最多十六人，村民也算在内）。',
  'adv.village': '村庄生活：村民知道附近真实存在的地方。问问他们"附近有什么好玩的地方？"，他们可能会告诉你沙漠神殿、林地府邸或者废弃矿井在哪儿，屏幕上会一直标着，直到你走到那里（暂停菜单里可以取消标记）。村民之间会聊天，好朋友路过会挥手，你打跑怪物他们会欢呼，拆他们的房子他们会生气，打雷时会跑回家，你从天上落下来他们会围过来看。',
});
